### ISSUE TITLE
'n a b/' creates file 'a' and dir 'b'

### ISSUE THREAD

**Issue by leo-arch** [leo-arch/CliFM#225]
**Describe the bug**
Issuing `n 'a b/'` creates a regular file named `a` and a directory named `b`, when it should create a single directory named `a b`.

Reported by @tkossak (#224)

**Comment by leo-arch** [comment]
For the time being, there are three ways to accomplish this:

1. `md "a b"`
2. `n a\ b/`
3.
```
n
> a b/
```

**Comment by leo-arch** [comment]
Hey @tkossak, it should be working now. Please give it a shot and let me know if any issue comes out.

**Comment by tkossak** [comment]
It works, thank you!

Btw. I didn't notice it in previous v1.12.2 version, but in v1.12.6 I get warning when creating folders with only number in their names eg: `n /tmp/7/` gives me:
```
7: Reserved (internal: ELN/range expansion)
new: /tmp/7/: Unsafe file name
Continue? [y/n]
```
Is it supposed to work like this?

Even if create it, enter its dir and create any file, it still warns me, because my CWD contains number:
```
> cd /tmp/7
> n a
7: Reserved (internal: ELN/range expansion)
new: /tmp/7/a: Unsafe file name
Continue? [y/n]
```

A bit annoying...

**Comment by leo-arch** [comment]
Yes, it is intended. I was reading about unsafe file names (https://dwheeler.com/essays/fixing-unix-linux-filenames.html) and decided to implement a little security check. Still experimental though.

In you specific case, the name `7` is considered unsafe because it might be expanded to the wrong file name if it happens to be 7 or more files in the current directory.

**Comment by tkossak** [comment]
How do I know if the number gets expanded or not? So far I was sure that if number is not alone (eg. is part of path) it never gets expanded to not go in my way. It seems like it's still not expanded, even if this ELN already exists:

```
<0> $ mkdir /tmp/1
T9[1] 16:14 kossak:lman3 /tmp/7
<0> $ /tmp/1
. ..
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
T9[1] 16:14 kossak:lman3 /tmp/1
<0> $ n a
1: Reserved (internal: ELN/range expansion)
new: /tmp/1/a: Unsafe file name
Continue? [y/n] y
1 a  ./rw-.r--.r-- 1000:1000 maj 29 16:14 0B
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
a
-> 1 file(s) created
T9[1] 16:14 kossak:lman3 /tmp/1
<0> $ n b
1: Reserved (internal: ELN/range expansion)
new: /tmp/1/b: Unsafe file name
Continue? [y/n] y
1 a  ./rw-.r--.r-- 1000:1000 maj 29 16:14 0B
2 b  ./rw-.r--.r-- 1000:1000 maj 29 16:14 0B
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
b
-> 1 file(s) created
T9[1] 16:14 kossak:lman3 /tmp/1
<0> $ n 2/
1: Reserved (internal: ELN/range expansion)
new: /tmp/1/2/: Unsafe file name
Continue? [y/n] y
1 2  - d/rwx.r-x.r-x 1000:1000 maj 29 16:18 0B
2 a  - ./rw-.r--.r-- 1000:1000 maj 29 16:14 0B
3 b  - ./rw-.r--.r-- 1000:1000 maj 29 16:14 0B
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2/
-> 1 file(s) created
T9[1] 16:18 kossak:lman3 /tmp/1

```

**Comment by leo-arch** [comment]
> So far I was sure that if number is not alone (eg. is part of path) it never gets expanded to not go in my way

This is true.

In case of base names, numbers are expanded only provided there's no file in the current directory named like that: if you enter `1` and there's a file named `1`, besides a directory named `dir/` whose ELN is `1`, the former takes precedence (the file named `1` is opened).

However, this might not be your original intention, and this is were the thing might be ambiguous (**clifm** cannot know in advance what was your intention).

**Comment by tkossak** [comment]
sorry, tested it in wrong version... let me repeat....

**Comment by tkossak** [comment]
The new behaviour seems more annoying for me. In clifm v1.12.2 I always knew if alone number gets expanded or not (it always was). In v1.12.6 it actually depends on the folder content so I never know if what I write will be expanded or not, until I check what current folder contains...  And It didn't warn me when I tried accessing folder by ELN number, only during creation:

```
T9[1] 16:42 kossak:lman3 /tmp/testdir
<0> $ n 0/ 1/ 2/
0: Reserved (internal: ELN/range expansion)
new: /tmp/testdir/0/: Unsafe file name
Continue? [y/n] y
1: Reserved (internal: ELN/range expansion)
new: /tmp/testdir/1/: Unsafe file name
Continue? [y/n] y
2: Reserved (internal: ELN/range expansion)
new: /tmp/testdir/2/: Unsafe file name
Continue? [y/n] y
1 0  - d/rwx.r-x.r-x 1000:1000 maj 29 16:42 0B
2 1  - d/rwx.r-x.r-x 1000:1000 maj 29 16:43 0B
3 2  - d/rwx.r-x.r-x 1000:1000 maj 29 16:43 0B
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0/
1/
2/
-> 3 file(s) created
T9[1] 16:43 kossak:lman3 /tmp/testdir
<0> $ readlink -f 1
/tmp/testdir/1
T9[1] 16:43 kossak:lman3 /tmp/testdir
<0> $ r 1/
rm: remove 1 argument recursively? y
1 0  - d/rwx.r-x.r-x 1000:1000 maj 29 16:42 0B
2 2  - d/rwx.r-x.r-x 1000:1000 maj 29 16:43 0B
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1/
-> 1 file(s) removed
T9[1] 16:49 kossak:lman3 /tmp/testdir
<0> $ readlink -f 1
/tmp/testdir/0
T9[1] 16:49 kossak:lman3 /tmp/testdir
<0> $

```

**Comment by leo-arch** [comment]
In case of ELN's, this new behavior might be securely reverted (always expand numbers if there's such an ELN). The feature is intended to prevent dangerous expansions, mostly multi-file expansions, say `sel`, `1-3`, `b:`, and so on. For example, if there's a file named `sel` in you current directory and you want to remove it, you might end up removing all your selected files. In this case, it is always better to err from the less dangerous side (removing only one file). But, since ELN's expand always to a single file, there's no such risk.

**Comment by leo-arch** [comment]
Done. ELN's are always expanded, disregarding the contents of the current directory. This gives a more predictable behavior. Thanks for the suggestion.

**Comment by tkossak** [comment]
Thank you very much! This predictability gives me peace of mind, when I write my commands, that I know beforehand what will be executed :). And if I want direct file/dir names (with numbers) I can always write the number in quotes like: `readlink -f '1'` and I know 1 will not be expanded.

**Comment by leo-arch** [comment]
You can also just quote or escape a number if you don't want it expanded: `"1"` and `\1` won't be exanded, while `1` will.

**Comment by leo-arch** [comment]
Little modification to the new warning about unsafe names: it now applies only to the actually entered name, and not the expanded absolute path. Example:

```
n 1/file
```
will emit a warning about `1`. But this:

```
cd 1
n file
```
will not.

This makes the feature less intrusive (thanks again for pointing it out).
